---
- name: Soft
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: url
      prompt: "Type of link to download" 
      private: no

  vars:
    path_win: C:\Temp\install.msi

  tasks:
    - name: Download Soft to host
      win_get_url:
        url: "{{ url }}"
        dest: "{{ path_win }}" 

    - name: Install Soft
      win_shell: Install-Package "{{ path_win }}" -force
